name: todo_app
description: todo app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.2
  uuid: ^3.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  freezed: ^2.1.1
flutter:
  uses-material-design: true
